name: Deploy Namespace with Terraform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_name_namespace: feature-namespace
          TF_VAR_label_namespace: demo-namespace

    
      
            
    
      
          

    
      
      
        

        
        

        
    

    
      
      
      

    



    

         

