name: Test Terraform Resources

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Verify Cluster Access
        run: kubectl cluster-info
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

       - name: Debug Kubeconfig
        run: cat $HOME/.kube/config
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}



      - name: Deploy Terraform Modules
        run: |
          cd modules/namespace
          terraform init
          terraform apply -auto-approve

          cd ../cluster-roles
          terraform init
          terraform apply -auto-approve

          cd ../roles
          terraform init
          terraform apply -auto-approve

          cd ../networkpolicy
          terraform init
          terraform apply -auto-approve

          # Add environment variables here if needed

      - name: Check ClusterRoles
        run: |
          kubectl get clusterroles

      - name: Check Namespaces
        run: |
          kubectl get namespaces

      - name: Check Roles
        run: |
          kubectl get roles --all-namespaces

      - name: Check NetworkPolicies
        run: |
          kubectl get networkpolicies --all-namespaces




      
          

    
      
      
        

        
        

        
    

    
      
      
      

    



    

         

