name: Check Helm and Gatekeeper Installation

on:
  push:
    branches:
      - main

jobs:
  check_helm_and_gatekeeper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm version

    - name: Check Helm version
      run: |
        helm version

    - name: Add Gatekeeper Helm repository
      run: |
        helm repo add gatekeeper https://open-policy-agent.github.io/gatekeeper/charts
        helm repo update

    - name: Install Gatekeeper using Helm
      run: |
        helm install gatekeeper gatekeeper/gatekeeper --namespace gatekeeper-system

    - name: Check Gatekeeper installation
      run: |
         kubectl get pods -n gatekeeper-system 
         

