name: Test Terraform Resources

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conntrack
        run: |
          sudo apt-get update
          sudo apt-get install conntrack

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Set up Minikube
        run: |
          minikube start --vm-driver=none
          minikube addons enable ingress

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Deploy Terraform Modules
        run: |
          cd modules/cluster-roles
          terraform init
          terraform apply -auto-approve

          cd ../namespace
          terraform init
          terraform apply -auto-approve

          cd ../roles
          terraform init
          terraform apply -auto-approve

          cd ../networkpolicy
          terraform init
          terraform apply -auto-approve

          # Add environment variables here if needed

      - name: Check ClusterRoles
        run: |
          kubectl get clusterroles

      - name: Check Namespaces
        run: |
          kubectl get namespaces

      - name: Check Roles
        run: |
          kubectl get roles --all-namespaces

      - name: Check NetworkPolicies
        run: |
          kubectl get networkpolicies --all-namespaces




      
          

    
      
      
        

        
        

        
    

    
      
      
      

    



    

         

