name: Test Terraform Resources

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          # Set up Minikube here

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Deploy Terraform Modules
        run: |
          cd modules/cluster-roles
          terraform init
          terraform apply -auto-approve

          cd ../namespace
          terraform init
          terraform apply -auto-approve

          cd ../roles
          terraform init
          terraform apply -auto-approve

          cd ../networkpolicy
          terraform init
          terraform apply -auto-approve

        env:
          # Set any environment variables needed for your modules

      - name: Check ClusterRoles
        run: |
          kubectl get clusterroles

      - name: Check Namespaces
        run: |
          kubectl get namespaces

      - name: Check Roles
        run: |
          kubectl get roles --all-namespaces

      - name: Check NetworkPolicies
        run: |
          kubectl get networkpolicies --all-namespaces


      
          

    
      
      
        

        
        

        
    

    
      
      
      

    



    

         

